package com.loyaltyworks.wavinseapp.model

import com.squareup.moshi.JsonClass
import java.io.Serializable


@JsonClass(generateAdapter = true)
data class CustomerDetailsRequest(
    var ActionType: String? = null,
    var ActiveStatus: String? = null,
    var ActorId: String? = null,
    var CustomerGradId: String? = null,
    var FromDate: String? = null,
    var ToDate: String? = null,
    var IsVerified: String? = null,
    val LocationId: String? = null,
    var MaxPointRange: String? = null,
    var MerchantID: String? = null,
    var MinPointRange: String? = null,
    var PageSize: String? = null,
    var Type: String? = null,
    val StartIndex: String? = null
)

@JsonClass(generateAdapter = true)
data class CustomerDetailsResponse(
    val AudienceOptimizationId: Any? = null,
    val BindYearWiseAttendanceList: Any? = null,
    val CustomerBasicInfoList: Any? = null,
    val CustomerDetailsResponseJson: List<CustomerDetailsResponseJson>? = null,
    val CustomerFamilyList: Any? = null,
    val CustomerMappingList: Any? = null,
    val CustomerOptimizationDetailsList: Any? = null,
    val CustomerPreferenceList: Any? = null,
    val HierarchyMapDetails: Any? = null,
    val HierarchyMapDetailsList: Any? = null,
    val LstCustomerPaymentModeDetails: Any? = null,
    val LstWorkSiteInfoDetails: Any? = null,
    val MappedCustomersList: Any? = null,
    val MappedProductList: Any? = null,
    val ObjCustomer: Any? = null,
    val ObjCustomerDetails: Any? = null,
    val ObjCustomerOfficalInfo: Any? = null,
    val PointBal: Any? = null,
    val ReturnMessage: Any? = null,
    val ReturnValue: Int? = null,
    val SubscriptionDetails: Any? = null,
    val TotEarned: Any? = null,
    val TotPointExpired: Any? = null,
    val TotRedeem: Any? = null,
    val TotSalesReturn: Any? = null,
    val TotalRecords: Int? = null,
    val lstCustomer: Any? = null,
    val lstCustomerEntityMapping: Any? = null,
    val lstCustomerIdentityInfo: Any? = null,
    val lstCustomerRemarksHistory: Any? = null,
    val lstCustomerSearchDetails: Any? = null,
    val lstRewardTransDetails: Any? = null,
    val lstRewardTransactionBasedonProduct: Any? = null,
    val lstVehicleDetails: Any? = null
)

@JsonClass(generateAdapter = true)
data class CustomerDetailsResponseJson(
    val AccountNumber: Any? = null,
    val AcountHolderName: Any? = null,
    val Address: Any? = null,
    val AreaId: Int? = null,
    val AreaName: Any? = null,
    val AsmName: String? = null,
    val AsmUserId: Int? = null,
    val BankBranch: Any? = null,
    val BankName: Any? = null,
    val CityId: Int? = null,
    val CityName: String? = null,
    val CountryName: String? = null,
    val CreatedById: Int? = null,
    val CreatedByName: String? = null,
    val CreatedDate: String? = null,
    val CustomerCategory: Any? = null,
    val CustomerCategoryId: Int? = null,
    val CustomerGrade: String? = null,
    val CustomerId: Int? = null,
    val CustomerTicketId: Int? = null,
    val Customer_Type: String? = null,
    val DepartmentId: Int? = null,
    val DesignationId: Int? = null,
    val DistrictId: Int? = null,
    val DistrictName: Any? = null,
    val Email: String? = null,
    val FullName: String? = null,
    val IFSCCode: Any? = null,
    val IsActive: Boolean? = null,
    val LocationId: Int? = null,
    val LocationName: String? = null,
    val LoyaltyId: String? = null,
    val MappedCount: String? = null,
    val MerchantID: Int? = null,
    val Mobile: String? = null,
    val PointsBalance: Int? = null,
    val ProfilePicture: String? = null,
    val Row: Int? = null,
    val SeName: String? = null,
    val SeUserId: Int? = null,
    val TalukId: Int? = null,
    val TalukName: Any? = null,
    val TicketReferenceNumber: Any? = null,
    val TotalRows: Int? = null,
    val UserId: Int? = null,
    val UserOneHeader: String? = null,
    val UserTwoHeader: String? = null,
    val Verified: Int? = null,
    val VerifiedName: String? = null,
    val VerifiedTypeId: Int? = null,
    val WalletNumber: Any? = null,
    val WhatsAppMobileNumber: Any? = null

): Serializable